name: CI

on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:

jobs:
  screenshots:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        branch: [main, ubuntu/lunar]
        theme: [light, dark, high-contrast-light, high-contrast-dark]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{matrix.branch}}

      - name: Clone ubuntu-desktop-installer
        uses: actions/checkout@v3
        with:
          ref: ${{matrix.branch}}
          submodules: recursive
          path: ubuntu-desktop-installer
          repository: canonical/ubuntu-desktop-installer

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip xvfb
          sudo apt install -y dbus-x11 fonts-ubuntu network-manager upower
          make install_deps
        working-directory: ubuntu-desktop-installer/packages/subiquity_client/subiquity

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.7.x'

      - name: Prepare environment
        run: |
          sudo loginctl enable-linger $USER
          sudo systemctl start user@$UID.service
          echo "XDG_RUNTIME_DIR=/run/user/$UID" >> $GITHUB_ENV
          # write any setting to force-start dconf.service (via xvfb because dbus-launch needs a display)
          xvfb-run -a gsettings set org.gnome.desktop.interface color-scheme "'default'"

      - name: Dump screenshots
        run: |
          xvfb-run -a -s '-screen 0 1024x768x24 +extension GLX' \
            flutter test --update-goldens integration_test/screenshot_test.dart
        working-directory: ubuntu-desktop-installer/packages/ubuntu_desktop_installer
        env:
          SUBIQUITY_REPLAY_TIMESCALE: 100
          UDI_SCREENSHOT_THEME: ${{matrix.theme}}

      - name: Sync screenshots
        run: |
          rsync -avu --delete ubuntu-desktop-installer/packages/ubuntu_desktop_installer/integration_test/screenshots/${{matrix.theme}} .

      - uses: peter-evans/create-pull-request@v5
        id: pr
        with:
          title: 'Update ${{matrix.theme}} screenshots on `${{matrix.branch}}`'
          commit-message: 'Update ${{matrix.theme}} screenshots on `${{matrix.branch}}`'
          author: GitHub <noreply@github.com>
          add-paths: ${{matrix.theme}}
          branch: pr/${{matrix.branch}}/${{matrix.theme}}
          delete-branch: true

      - run: gh pr merge --squash ${{steps.pr.outputs.pull-request-number}}
        if: (steps.pr.outputs.pull-request-operation == 'created') || (steps.pr.outputs.pull-request-operation == 'updated')
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
